apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charts.fullname" . }}-nginx-conf
  labels:
    {{- include "charts.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 80;
      location / {
        return 200 'Hello, world!';
        add_header Content-Type text/plain;
      }
    }
