apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-1.fullname" . }}
  labels:
    {{- include "hello-1.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hello-1.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-1.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "nginx:1.14.2"
          ports:
            - name: http
              containerPort: {{ .Values.container.port }} # Use container port from values.yaml
              protocol: TCP
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ include "hello-1.fullname" . }}-nginx-conf
