apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}--service
  labels:
    {{- include "hello-1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: hello-1
