apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}--deployment-{{ .Chart.Version }}"
  labels:
    {{- include "hello-3.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hello-3.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-3.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "nginx:1.14.2"
          ports:
            - name: http
              containerPort: {{ .Values.container.port }} # Use container port from values.yaml
              protocol: TCP
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
            - name: html 
              mountPath: /usr/share/nginx/html 
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ .Release.Name }}--nginx-conf
        - name: html 
          configMap:
            name: {{ .Release.Name }}--configmap
