apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}--configmap
data:
  index.html: |-
    {
      "chart": "{{ .Chart.Name }}",
      "version": "{{ .Chart.Version }}"
      "releaseName": "{{ .Release.Name }}" 
      "appVersion": "{{ .Chart.AppVersion }}"
    }
